/*
 * @Date: 2025-03-31 22:36:55
 * @LastEditors: 陶浩南 taoaaron5@gmail.com
 * @LastEditTime: 2025-06-29 17:02:03
 * @FilePath: /Money_Recorder/constants/languages.ts
 */
// 定义所有界面文本的中英文翻译

export const zhCN = {
  home: {
    search: "搜索",
    monthlyIncome: "月收入",
    monthlyExpense: "月支出",
    recentRecords: "最近记录",
    monthlyNetIncome: "月净收入",
    enterBudget: "请输入新的预算金额：",
  },
  goals: {
    title: "存款目标",
    noData: "暂无存款目标",
  },
  settings: {
    title: "设置",
    notifications: "通知",
    theme: "主题",
    themeLight: "浅色",
    themeDark: "深色",
    clearCache: "清除缓存",
    language: "语言",
    version: "应用版本",
  },
  record: {
    title: "记录",
    amount: "金额",
    type: "类型",
    category: "类型",
    date: "日期",
    method: "支付方式",
    location: "位置",
    tags: "标签",
    comment: "备注",
    income: "收入",
    expense: "支出",
    none: "未找到记录",
  },
  stats: {
    title: "统计",
    income: "收入",
    expense: "支出",
    total: "总计",
    records: "记录数",
    pieChart: "分类占比",
    barChart: "月度趋势",
    noData: "暂无数据",
    refresh: "刷新",
    loading: "加载中...",
    switchToIncome: "切换到收入",
    switchToExpense: "切换到支出",
    setBudget: "设置预算",
  },
  common: {
    cancel: "取消",
    confirm: "确认",
    success: "成功",
    error: "错误",
    open: "打开",
    clear: "清除",
    all: "全部",
    income: "收入",
    expense: "支出",
  },
  alerts: {
    deleteTransaction: {
      title: "删除交易",
      message: "确定要删除此交易吗？此操作无法撤销。",
      success: "交易删除成功！",
      error: "删除交易失败。",
    },
    clearCache: {
      title: "清除缓存",
      message: "确定要清除缓存吗？此操作无法撤销。",
      success: "缓存清除成功！",
      error: "清除缓存失败。",
    },

    notifications: {
      title: "通知设置",
      message: "是否打开通知设置？",
      iosOnly: "此功能仅在iOS设备上可用。",
    },
    budget: {
      deleteTitle: "删除预算",
      deleteMessage: "确定要删除此预算吗？此操作无法撤销。",
      updateTitle: "更新预算",
      updateMessage: "确定要保存这些更改吗？",
    },
  },
  categories: {
    total: "总计",
    eating: "饮食",
    traffic: "交通",
    shopping: "购物",
    entertainment: "娱乐",
    living: "生活",
    medication: "医疗",
    education: "教育",
    others: "其他",
    salary: "工资",
    sideline: "兼职",
    investment: "投资",
    bonus: "奖金",
    other: "其他",
    card: "银行卡",
    transfer: "转账",
    cash: "现金",
  },
};

export const enUS = {
  home: {
    search: "Search",
    monthlyIncome: "Monthly Income",
    monthlyExpense: "Monthly Expense",
    recentRecords: "Recent Records",
    monthlyNetIncome: "Monthly Net Income",
    enterBudget: "Enter new budget amount:",
  },
  goals: {
    title: "Deposit Goal",
    noData: "No deposit goals yet, click the button below to add",
  },
  settings: {
    title: "Settings",
    notifications: "Notifications",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    clearCache: "Clear Cache",
    language: "Language",
    version: "App Version",
  },
  record: {
    title: "Record",
    amount: "Amount",
    type: "Type",
    category: "Category",
    date: "Date",
    method: "Payment Method",
    location: "Location",
    tags: "Tags",
    comment: "Comment",
    income: "Income",
    expense: "Expense",
    none: "Record not found",
  },
  stats: {
    title: "Statistics",
    income: "Income",
    expense: "Expense",
    total: "Total",
    records: "Records",
    pieChart: "Category Distribution",
    barChart: "Monthly Trend",
    noData: "No Created Data",
    refresh: "Refresh",
    loading: "Loading...",
    switchToIncome: "Switch to Income",
    switchToExpense: "Switch to Expense",
    setBudget: "Set Budget",
  },
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    success: "Success",
    error: "Error",
    open: "Open",
    clear: "Clear",
    all: "All",
    income: "Income",
    expense: "Expense",
  },
  alerts: {
    deleteTransaction: {
      title: "Delete Transaction",
      message:
        "Are you sure you want to delete this transaction? This action cannot be undone.",
      success: "Transaction deleted successfully!",
      error: "Failed to delete transaction.",
    },
    clearCache: {
      title: "Clear Cache",
      message:
        "Are you sure you want to clear the cache? This action cannot be undone.",
      success: "Cache cleared successfully!",
      error: "Failed to clear cache.",
    },
    notifications: {
      title: "Notifications Settings",
      message: "Open the Notification settings?",
      iosOnly: "This functionality is only available on iOS.",
    },
    budget: {
      deleteTitle: "Delete Budget",
      deleteMessage:
        "Are you sure you want to delete this budget? This action cannot be undone.",
      updateTitle: "Update Budget",
      updateMessage: "Are you sure you want to save these changes?",
    },
  },
  categories: {
    total: "Total",
    eating: "Eating",
    traffic: "Traffic",
    shopping: "Shopping",
    entertainment: "Entertainment",
    living: "Living",
    medication: "Medication",
    education: "Education",
    others: "Others",
    salary: "Salary",
    sideline: "Sideline",
    investment: "Investment",
    bonus: "Bonus",
    other: "Other",
  },
};
